/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef DISP_H
#define DISP_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM (168863250) /* 0xa10a612 */
#define CAN_ID_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT (168870429) /* 0xa10c21d */
#define CAN_ID_DISP_STEUERUNG_HK1_DAUERBETRIEB (168895006) /* 0xa11221e */
#define CAN_ID_DISP_STEUERUNG_HK1_WAERMER_KAELTER (168895012) /* 0xa112224 */
#define CAN_ID_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM (303088153) /* 0x1210c219 */
#define CAN_ID_DISP_STEUERUNG_HK1_SOMMERBETRIEB (303112723) /* 0x12112213 */
#define CAN_ID_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT (303112735) /* 0x1211221f */
#define CAN_ID_DISP_STEUERUNG_HK1_PROGRAMM (303112738) /* 0x12112222 */
#define CAN_ID_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART (314098189) /* 0x12b8c20d */

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT; /* scaling 0.1, offset 0.0, units °C  */
} POSTPACK can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_HK1_DAUERBETRIEB; /* scaling 1.0, offset 0.0, units Stunden  */
} POSTPACK can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_HK1_WAERMER_KAELTER; /* scaling 0.1, offset 0.0, units °C  */
} POSTPACK can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_HK1_SOMMERBETRIEB; /* scaling 0.1, offset 0.0, units °C  */
} POSTPACK can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_HK1_ABWESENHEITSZEIT; /* scaling 1.0, offset 0.0, units Tage  */
} POSTPACK can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_HK1_PROGRAMM; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_t;

typedef PREPACK struct {
	int16_t DISP_STEUERUNG_FESTBRENNOFEN_HOLZART; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_time_stamp_rx;
	dbcc_time_stamp_t can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_time_stamp_rx;
	dbcc_time_stamp_t can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_time_stamp_rx;
	dbcc_time_stamp_t can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_time_stamp_rx;
	dbcc_time_stamp_t can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_time_stamp_rx;
	dbcc_time_stamp_t can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_time_stamp_rx;
	dbcc_time_stamp_t can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_time_stamp_rx;
	dbcc_time_stamp_t can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_time_stamp_rx;
	dbcc_time_stamp_t can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_time_stamp_rx;
	unsigned can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_status : 2;
	unsigned can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_tx : 1;
	unsigned can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_rx : 1;
	unsigned can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_status : 2;
	unsigned can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_tx : 1;
	unsigned can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_rx : 1;
	unsigned can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_status : 2;
	unsigned can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_tx : 1;
	unsigned can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_rx : 1;
	unsigned can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_status : 2;
	unsigned can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_tx : 1;
	unsigned can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_rx : 1;
	unsigned can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_status : 2;
	unsigned can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_tx : 1;
	unsigned can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_rx : 1;
	unsigned can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_status : 2;
	unsigned can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_tx : 1;
	unsigned can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_rx : 1;
	unsigned can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_status : 2;
	unsigned can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_tx : 1;
	unsigned can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_rx : 1;
	unsigned can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_status : 2;
	unsigned can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_tx : 1;
	unsigned can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_rx : 1;
	unsigned can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_status : 2;
	unsigned can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_tx : 1;
	unsigned can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_rx : 1;
	can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_t can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM;
	can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT_t can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT;
	can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB_t can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB;
	can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER_t can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER;
	can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM_t can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM;
	can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB_t can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB;
	can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT_t can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT;
	can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM_t can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM;
	can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART_t can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART;
} POSTPACK can_obj_disp_h_t;

int unpack_message(can_obj_disp_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_disp_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_disp_h_t *o, const unsigned long id, FILE *output);

int decode_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(can_obj_disp_h_t *o, int16_t in);


int decode_can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT(const can_obj_disp_h_t *o, double *out);
int encode_can_0xa10c21d_DISP_STEUERUNG_WW_SOLLTEMPERATUR_PWT(can_obj_disp_h_t *o, double in);


int decode_can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0xa11221e_DISP_STEUERUNG_HK1_DAUERBETRIEB(can_obj_disp_h_t *o, int16_t in);


int decode_can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER(const can_obj_disp_h_t *o, double *out);
int encode_can_0xa112224_DISP_STEUERUNG_HK1_WAERMER_KAELTER(can_obj_disp_h_t *o, double in);


int decode_can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0x1210c219_DISP_STEUERUNG_WW_ZIRKULATIONSPROGRAMM(can_obj_disp_h_t *o, int16_t in);


int decode_can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB(const can_obj_disp_h_t *o, double *out);
int encode_can_0x12112213_DISP_STEUERUNG_HK1_SOMMERBETRIEB(can_obj_disp_h_t *o, double in);


int decode_can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0x1211221f_DISP_STEUERUNG_HK1_ABWESENHEITSZEIT(can_obj_disp_h_t *o, int16_t in);


int decode_can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0x12112222_DISP_STEUERUNG_HK1_PROGRAMM(can_obj_disp_h_t *o, int16_t in);


int decode_can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART(const can_obj_disp_h_t *o, int16_t *out);
int encode_can_0x12b8c20d_DISP_STEUERUNG_FESTBRENNOFEN_HOLZART(can_obj_disp_h_t *o, int16_t in);


#ifdef __cplusplus
} 
#endif

#endif
