/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "disp.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(can_obj_disp_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM: start-bit 15, length 16, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM.DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM)) & 0xffff;
	x <<= 40; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_tx = 1;
	return 4;
}

static int unpack_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(can_obj_disp_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 4)
		return -1;
	/* DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM: start-bit 15, length 16, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0xffff;
	o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM.DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM = x;
	o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_rx = 1;
	o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_time_stamp_rx = time_stamp;
	return 4;
}

int decode_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(const can_obj_disp_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM.DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM);
	*out = rval;
	return 0;
}

int encode_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(can_obj_disp_h_t *o, int16_t in) {
	assert(o);
	o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM.DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM = in;
	return 0;
}

int print_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(const can_obj_disp_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM = (wire: %.0f)\n", (double)(o->can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM.DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM)));
	return r;
}

int unpack_message(can_obj_disp_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0xa10a612: return unpack_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_disp_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0xa10a612: return pack_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_disp_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0xa10a612: return print_can_0xa10a612_DISP_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(o, output);
	default: break; 
	}
	return -1; 
}

