/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef EOS7_H
#define EOS7_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM (470852626) /* 0x1c10a412 */
#define CAN_ID_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR (481845248) /* 0x1cb86000 */
#define CAN_ID_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR (481845249) /* 0x1cb86001 */
#define CAN_ID_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU (481845256) /* 0x1cb86008 */
#define CAN_ID_EOS7_STATUS_FESTBRENNOFEN_HOLZART (481869837) /* 0x1cb8c00d */
#define CAN_ID_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS (481869838) /* 0x1cb8c00e */

typedef PREPACK struct {
	int16_t EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_t;

typedef PREPACK struct {
	int16_t EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR; /* scaling 0.1, offset 0.0, units °C  */
} POSTPACK can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_t;

typedef PREPACK struct {
	int16_t EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR; /* scaling 0.1, offset 0.0, units °C  */
} POSTPACK can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_t;

typedef PREPACK struct {
	int16_t EOS7_STATUS_FESTBRENNOFEN_TUER_ZU; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_t;

typedef PREPACK struct {
	int16_t EOS7_STATUS_FESTBRENNOFEN_HOLZART; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_t;

typedef PREPACK struct {
	int16_t EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_time_stamp_rx;
	dbcc_time_stamp_t can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_time_stamp_rx;
	dbcc_time_stamp_t can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_time_stamp_rx;
	dbcc_time_stamp_t can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_time_stamp_rx;
	dbcc_time_stamp_t can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_time_stamp_rx;
	dbcc_time_stamp_t can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_time_stamp_rx;
	unsigned can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_status : 2;
	unsigned can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_tx : 1;
	unsigned can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_rx : 1;
	unsigned can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_status : 2;
	unsigned can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_tx : 1;
	unsigned can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_rx : 1;
	unsigned can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_status : 2;
	unsigned can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_tx : 1;
	unsigned can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_rx : 1;
	unsigned can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_status : 2;
	unsigned can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_tx : 1;
	unsigned can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_rx : 1;
	unsigned can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_status : 2;
	unsigned can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_tx : 1;
	unsigned can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_rx : 1;
	unsigned can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_status : 2;
	unsigned can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_tx : 1;
	unsigned can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_rx : 1;
	can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM_t can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM;
	can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR_t can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR;
	can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR_t can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR;
	can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU_t can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU;
	can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART_t can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART;
	can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS_t can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS;
} POSTPACK can_obj_eos7_h_t;

int unpack_message(can_obj_eos7_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_eos7_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_eos7_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(const can_obj_eos7_h_t *o, int16_t *out);
int encode_can_0x1c10a412_EOS7_STEUERUNG_ZUSATZHEIZUNG_PROGRAMM(can_obj_eos7_h_t *o, int16_t in);


int decode_can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR(const can_obj_eos7_h_t *o, double *out);
int encode_can_0x1cb86000_EOS7_TEMPERATUR_FESTBRENNOFEN_BRENNRAUMTEMPERATUR(can_obj_eos7_h_t *o, double in);


int decode_can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR(const can_obj_eos7_h_t *o, double *out);
int encode_can_0x1cb86001_EOS7_TEMPERATUR_FESTBRENNOFEN_KESSELTEMPERATUR(can_obj_eos7_h_t *o, double in);


int decode_can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU(const can_obj_eos7_h_t *o, int16_t *out);
int encode_can_0x1cb86008_EOS7_STATUS_FESTBRENNOFEN_TUER_ZU(can_obj_eos7_h_t *o, int16_t in);


int decode_can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART(const can_obj_eos7_h_t *o, int16_t *out);
int encode_can_0x1cb8c00d_EOS7_STATUS_FESTBRENNOFEN_HOLZART(can_obj_eos7_h_t *o, int16_t in);


int decode_can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS(const can_obj_eos7_h_t *o, int16_t *out);
int encode_can_0x1cb8c00e_EOS7_STATUS_FESTBRENNOFEN_OEKOBETRIEB_AUS(can_obj_eos7_h_t *o, int16_t in);


#ifdef __cplusplus
} 
#endif

#endif
